- name: remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: apt clean
  shell: apt clean

- name: remove caches
  shell: find /var/cache -type f -exec rm -rf {} \;

- name: blank netplan machine-id
  shell: truncate -s 0 /etc/machine-id

- name: remove the files of /tmp and /var/tmp
  shell: rm -rf /tmp/* /var/tmp/*

- name: clear the history of the installer
  shell: |
    export HISTSIZE=0
    rm -f /root/.wget-hsts

- name: zero out root
  shell:
    count=`df --sync -kP / | tail -n1  | awk -F ' ' '{print $4}'`;
    let count--;
    dd if=/dev/zero of=/tmp/whitespace bs=1M count=${count};
    rm /tmp/whitespace;
