- name: Update and upgrade apt packages
  become: true
  apt:
    update_cache: yes

- name: Upgrade all apt packages
  become: true
  apt:
    upgrade: dist

- name: install open-vm-tools
  apt:
    update_cache: yes
    name: open-vm-tools

- name: disable auto updates
  command: sed -i -e "s/\"1\"/\"0\"/" /etc/apt/apt.conf.d/20auto-upgrades

