---
- name: Configure LDAP servers and clients using debconf
  hosts: all
  become: yes

  tasks:
  - name: Set debconf selections for slapd on LDAP servers
    ansible.builtin.debconf:
      name: slapd
      question: "{{ item.question }}"
      vtype: "{{ item.vtype }}"
      value: "{{ item.value }}"
    loop:
      - { question: 'slapd/no_configuration', vtype: 'boolean', value: 'false' }
      - { question: 'slapd/domain', vtype: 'string', value: 'mdx.jp' }
      - { question: 'slapd/password1', vtype: 'password', value: 'mdxuser1' }
      - { question: 'slapd/password2', vtype: 'password', value: 'mdxuser1' }
    when: "'control_nodes' in group_names"

  - name: Reconfigure slapd to apply debconf selections
    ansible.builtin.shell:
      cmd: dpkg-reconfigure -fnoninteractive slapd
    when: "'control_nodes' in group_names"

  - name: Update nslcd configuration for uri
    ansible.builtin.lineinfile:
      path: /etc/nslcd.conf
      regexp: '^uri\s+.*'
      line: "uri {{ ldap_server_uri }}"
    notify: restart nslcd

  - name: Update nslcd configuration for base
    ansible.builtin.lineinfile:
      path: /etc/nslcd.conf
      regexp: '^base\s+.*'
      line: "base dc=mdx,dc=jp"
    notify: restart nslcd

  - name: Update nsswitch.conf for LDAP support
    ansible.builtin.lineinfile:
      path: /etc/nsswitch.conf
      regexp: '^(passwd|group|shadow)\s*:.*'
      line: "\\1: files ldap"
      backrefs: yes
      state: present

  handlers:
  - name: restart nslcd
    ansible.builtin.service:
      name: nslcd
      state: restarted

- name: Edit common-session
  hosts: control_nodes
  become: yes
  tasks:
    - name: Add config for LDAP
      lineinfile:
        path: /etc/pam.d/common-session
        line: "session required pam_mkhomedir.so skel=/etc/skel/ umask=0022"
        state: present
