---
- name: Update /etc/hosts with other hosts
  hosts: all
  become: yes
  tasks:
    - name: Template /etc/hosts
      ansible.builtin.template:
        src: hosts.j2
        dest: /etc/hosts

- name: Configure SLURM for Control and Compute Nodes
  hosts: all
  become: yes
  tasks:
    - name: Ensure slurm.conf is present on all nodes
      copy:
        src: slurm.conf
        dest: /etc/slurm/slurm.conf
        owner: root
        group: root
        mode: '0644'

- name: Configure Control Node specific settings
  hosts: control_nodes
  become: yes
  tasks:
    - name: Ensure /var/spool/slurmctld exists
      file:
        path: /var/spool/slurmctld
        state: directory
        owner: slurm
        group: slurm
        mode: '0755'

    - name: Start munge service
      service:
        name: munge
        state: started
        enabled: yes

    - name: Start slurmctld service
      service:
        name: slurmctld
        state: started
        enabled: yes

    - name: Fetch munge.key to Ansible Controller
      fetch:
        src: /etc/munge/munge.key
        dest: /tmp/munge.key
        flat: yes

- name: Configure Compute Nodes specific settings
  hosts: compute_nodes
  become: yes
  tasks:
    - name: Ensure /var/spool/slurmd exists
      file:
        path: /var/spool/slurmd
        state: directory
        owner: slurm
        group: slurm
        mode: '0755'

    - name: Copy munge.key to Compute Nodes
      copy:
        src: /tmp/munge.key
        dest: /etc/munge/munge.key
        owner: munge
        group: munge
        mode: '0400'

    - name: Start munge service on Compute Nodes
      service:
        name: munge
        state: started
        enabled: yes

    - name: Start slurmd service on Compute Nodes
      service:
        name: slurmd
        state: started
        enabled: yes

- name: Restart munge service on all nodes
  hosts: all
  become: yes
  tasks:
    - name: Restart munge service
      service:
        name: munge
        state: restarted
