- name: remove /etc/cloud/cloud.cfg.d/99-installer.cfg
  file:
    path: /etc/cloud/cloud.cfg.d/99-installer.cfg
    state: absent

- name: create a cloud-init configuration file for mdx
  blockinfile:
    path: /etc/cloud/cloud.cfg.d/mdx.cfg
    create: yes
    marker: ""
    block: |
      datasource_list: [None]

